# Generated by Django 4.2.28 on 2026-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('lobo', 'Lobo'), ('lobo_albino', 'Lobo Albino'), ('lobo_padre', 'Lobo Padre'), ('aldeano', 'Aldeano'), ('arbol', 'Arbol'), ('cupido', 'Cupido'), ('bruja', 'Bruja'), ('nina_salvaje', 'Niña Salvaje'), ('cazador', 'Cazador'), ('vidente', 'Vidente')], default='aldeano', max_length=20)),
                ('esta_vivo', models.BooleanField(default=True)),
            ],
        ),
    ]
