# Generated by Django 4.2.28 on 2026-02-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6, unique=True)),
                ('partida_iniciada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='jugador',
            name='es_lider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jugador',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='juego.sala'),
        ),
    ]
