# Generated by Django 4.2.28 on 2026-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_sala_alter_jugador_options_jugador_es_lider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='configuracion_roles',
            field=models.JSONField(default=dict),
        ),
    ]
